version: '2'
services:
  postgres:
    image: mdillon/postgis:9.6
    ports:
      - 15432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cnefe
      - POSTGRES_USER=cnefe
      - POSTGRES_PASSWORD=cnefe